docs/user-guide/installation/installing-r2modman-linux.md
Forgot to remove a reference to custom songs after forking the Trombone Champ mod installation guide
=> Remove old "Custom Songs"

docs/navbar.md, index.html
- Sets up language selection at top of page
- Adds shorthand links to Russian translation
This process is very similar to how future translations will need to be added
=> Add Russian translation to site

docs/user-guide/modding/advanced/networking.md
Changed "Method" to nameof(Class.Method) at @legoandmars' recommendation to something more standard and with higher compatibility.
=> Updated Patching Method

docs/modding/initial-setup.md, docs/modding/starting-a-mod.md
- Fix dnSpy link to use dnSpyEx (#17)
- Add warning for .NET 8 SDK causing template error - this is a fairly common problem that is hard to figure out, so IMO it should just be baked into the wiki
=> Modding setup upkeep

docs/.vitepress/config.mts, docs/beginners-guide.md
Reverts LethalCompany/ModdingWiki#35
It do be breaking the site
=> Revert "Indexing fixes"

docs/.vitepress/config.mts
the 404 might have just been a settings misconfiguration. worth trying cleanUrls again to see if it works
=> Enable cleanurls again

docs/.vitepress/config.mts, docs/index.md
- Add an explicit path to the favicon so google will show it in results again
- Change index.md paths to remove the (.html) and prevent duplicate pages from appearing on the site
- Fix the "configuring mods" link being wrong on index.md
=> More site indexing fixes

docs/dev/starting-a-mod.md
See #57 for original;
Updated since file location changed due to #51
=> Add Publicize Info to Adding Game Assemblies

docs/index.md
Currently preventing GitHub from deploying website
=> Fix Dead Link in Homepage

docs/public/BingSiteAuth.xml
Adds a file to verify the site on [Bing Webmaster Tools](https://www.bing.com/webmasters) so we can get some site improvement data
=> Bing site auth

docs/dev/initial-setup.md
- added a note to install recommended Visual Studio version to reduce issues when users attempt to build their project
=> Specify Visual Studio Recommended Version

.github/workflows/build.yml, .github/workflows/deploy.yml
Allows for checks on PRs to prevent any future mishaps, such as dead links.
=> Separate CI & CD Workflows

docs/.vitepress/config.mts, docs/dev/apis/csync/usage-guide.md
=> FIX CSYNC SECTION

docs/dev/apis/lethallib/custom-enemies/blender-resources.md, docs/dev/apis/lethallib/custom-enemies/coding-ai.md, docs/dev/apis/lethallib/custom-enemies/unity-project.md
I have improved the guide based on issues people have had, including some other stuff. Minor changes.
=> Custom Enemies: Small clarifications and fixes

docs/dev/mod-testing-tips.md
Make the `Mod Testing Tips` page up-to-date with developments in development mods.
- [DevelopmentStartup](https://thunderstore.io/c/lethal-company/p/CTNOriginals/DevelopmentStartup/) now supports automatically joining local games
- [DevTools](https://thunderstore.io/c/lethal-company/p/Hamunii/DevTools/) by me (shameless plug) is now released (only works for host if Online, but for all clients in LAN), it offers helpful functionality for mod developers, and is listed as an alternative to [LethalDevMode](https://thunderstore.io/c/lethal-company/p/megumin/LethalDevMode/) under `Accessing The Debug/Test Menu`.
=> Mod Testing Tips: Up-to-date

docs/installation/installing-r2modman-linux.md
Add instructions for running r2modman in Steam Deck Game Mode. Altered references to running r2modman in Steam Deck Game Mode.
=> Using r2modman on Linux and Steam Deck: Add instructions for r2modman in Steam Deck Game Mode

docs/dev/fundamentals/patching-code/monomod-documentation.md
Fixes a minor whoopsie I have made, teehee :3c
=> MonoMod Docs: Fix: Link to DetourContext Dispose Fix on Lethal Company instead of Plasma

docs/dev/fundamentals/patching-code/monomod-examples.md
=> Fix incorrect type in MonoMod Examples article

docs/dev/intermediate/custom-configs.md
I attempted to make the custom configs page a bit easier to follow for beginners, and also make it at least somewhat explain why we do what we do.
Also now recommends CSync too, at the bottom of the page.
=> Improve Custom Configs Page

docs/dev/fundamentals/patching-code.md, docs/dev/fundamentals/patching-code/monomod-examples.md
The basic patch example is no longer a cheat, and I added some info and warning stuff
=> Patching Code: Mark old info, Change basic patch example & Add warning about cheats

docs/dev/initial-setup.md
https://blog.jetbrains.com/blog/2024/10/24/webstorm-and-rider-are-now-free-for-non-commercial-use/
=> JetBrains Rider is Now Free

docs/dev/apis/overview.md, translations/da_DK/docs/dev/apis/overview.md, translations/de_DE/docs/dev/apis/overview.md, translations/es_ES/docs/dev/apis/overview.md, translations/fi_FI/docs/dev/apis/overview.md, translations/fr_FR/docs/dev/apis/overview.md, translations/hu_HU/docs/dev/apis/overview.md, translations/it_IT/docs/dev/apis/overview.md, translations/ja_JP/docs/dev/apis/overview.md, translations/ko_KR/docs/dev/apis/overview.md, translations/nl_NL/docs/dev/apis/overview.md, translations/pl_PL/docs/dev/apis/overview.md, translations/pt_BR/docs/dev/apis/overview.md, translations/ru_RU/docs/dev/apis/overview.md, translations/th_TH/docs/dev/apis/overview.md, translations/uk_UA/docs/dev/apis/overview.md, translations/zh_CN/docs/dev/apis/overview.md
- LethalLib is documented on the wiki here: https://lethal.wiki/dev/apis/lethallib
- ConfigurableCompany is documented on the wiki here: https://lethal.wiki/dev/apis/configurable-company
So I added a gold star (⭐) to them, as stated here: https://lethal.wiki/dev/apis/overview
=> Mark LethalLib and ConfigurableCompany as documented on this wiki (⭐)
